# Generated by Django 3.1.7 on 2021-03-13 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_itinerary_trip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='date',
            field=models.DateField(verbose_name='Activity Date'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='arrive',
            field=models.DateField(verbose_name='return date'),
        ),
    ]
